import { registerAs } from '@nestjs/config';
import { NetworkConfig } from 'network/network.types';

const ankrKey = process.env.ANKR_KEY;
if (!ankrKey) throw new Error('ANKR_KEY was not provided!');

const quickNodeKey = process.env.UNICHAIN_QUICKNODE_KEY;
if (!quickNodeKey) throw new Error('UNICHAIN_QUICKNODE_KEY was not provided!');

export default registerAs('networks', (): NetworkConfig[] => [
  {
    network: 'mainnet',
    chainId: 1,
    url: `https://rpc.ankr.com/eth/${ankrKey}`,
    sortPosition: 1,
    blockscanOrigin: 'https://etherscan.io/',
    displayName: 'Ethereum Mainnet',
    comp: '0xc00e94cb662c3520282e6f5717214004a7f26888',
    svrFeeRecipient: '0xd9496f2a3fd2a97d8a4531d92742f3c8f53183cb',
  },
  {
    network: 'optimism',
    chainId: 10,
    url: `https://rpc.ankr.com/optimism/${ankrKey}`,
    sortPosition: 2,
    blockscanOrigin: 'https://optimistic.etherscan.io/',
    displayName: 'Optimism',
    comp: '0x7e7d4467112689329f7e06571ed0e8cbad4910ee',
  },
  {
    network: 'unichain',
    chainId: 130,
    url: `https://multi-boldest-patina.unichain-mainnet.quiknode.pro/${quickNodeKey}`,
    sortPosition: 3,
    blockscanOrigin: 'https://uniscan.xyz/',
    displayName: 'Unichain',
    comp: '0xdf78e4f0a8279942ca68046476919a90f2288656',
  },
  {
    network: 'polygon',
    chainId: 137,
    url: `https://rpc.ankr.com/polygon/${ankrKey}`,
    sortPosition: 4,
    blockscanOrigin: 'https://polygonscan.com/',
    displayName: 'Polygon Mainnet',
    comp: '0x8505b9d2254a7ae468c0e9dd10ccea3a837aef5c',
  },
  {
    network: 'ronin',
    chainId: 2020,
    url: 'https://ronin.drpc.org',
    batchMaxCount: 3,
    sortPosition: 5,
    blockscanOrigin: 'https://app.roninchain.com/',
    displayName: 'Ronin',
  },
  {
    network: 'mantle',
    chainId: 5000,
    url: `https://rpc.ankr.com/mantle/${ankrKey}`,
    sortPosition: 6,
    blockscanOrigin: 'https://mantlescan.xyz/',
    displayName: 'Mantle',
    comp: '0x52b7d8851d6ccbc6342ba0855be65f7b82a3f17f',
  },
  {
    network: 'base',
    chainId: 8453,
    url: `https://rpc.ankr.com/base/${ankrKey}`,
    sortPosition: 7,
    blockscanOrigin: 'https://basescan.org/',
    displayName: 'Base',
    comp: '0x9e1028f5f1d5ede59748ffcee5532509976840e0',
    svrFeeReceiver: '0xb3e79c7cac540ca833015e63d96d3032ba0c4129',
  },
  {
    network: 'arbitrum',
    chainId: 42161,
    url: `https://rpc.ankr.com/arbitrum/${ankrKey}`,
    sortPosition: 8,
    blockscanOrigin: 'https://arbiscan.io/',
    displayName: 'Arbitrum',
    comp: '0x354a6da3fcde098f8389cad84b0182725c6c91de',
    svrFeeReceiver: '0xb3e79c7cac540ca833015e63d96d3032ba0c4129',
  },
  {
    network: 'linea',
    chainId: 59144,
    url: `https://rpc.ankr.com/linea/${ankrKey}`,
    sortPosition: 9,
    blockscanOrigin: 'https://lineascan.build/',
    displayName: 'Linea',
    comp: '0x0ece76334fb560f2b1a49a60e38cf726b02203f0',
  },
  {
    network: 'scroll',
    chainId: 534352,
    url: `https://rpc.ankr.com/scroll/${ankrKey}`,
    sortPosition: 10,
    blockscanOrigin: 'https://scrollscan.com/',
    displayName: 'Scroll',
  },
  {
    network: 'avalanche',
    chainId: 43114,
    url: 'https://api.avax.network/ext/bc/C/rpc',
    sortPosition: 11,
    blockscanOrigin: 'https://snowtrace.io/',
    displayName: 'Avalanche',
  },
  {
    network: 'sepolia',
    chainId: 11155111,
    url: `https://rpc.ankr.com/eth_sepolia/${ankrKey}`,
    sortPosition: 12,
    blockscanOrigin: 'https://sepolia.etherscan.io/',
    displayName: 'Ethereum Sepolia Testnet',
  },
  {
    network: 'fuji',
    chainId: 43113,
    url: 'https://api.avax-test.network/ext/bc/C/rpc',
    sortPosition: 15,
    blockscanOrigin: 'https://testnet.snowtrace.io/',
    displayName: 'Avalanche Fuji Testnet',
  },
]);
